theme: jekyll-theme-cayman
title: Jacob Holcomb
description: A Computer Science and Mathematics double major at Southwest Baptist University
<a herf = "CS2Game.zip">Computer Science 2 Educational Game Project</a>
